spring.application.name=bkedgame

server.port = 8862

spring.datasource.url=${url_bd}
spring.datasource.username=${usuario_bd}
spring.datasource.password=${clave_bd}
spring.jpa.hibernate.ddl-auto=${ddl_hibernate}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

